spring:
  application:
    name: homework
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum
    username: root
    password: LinKangYang@2003
mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 3000

file:
  storage:
    location: F:/Desktop/Fall2025/Software/homework/Demo/server/storage/